/**
 * 用語集の正本。レッスン本文の <Terms ids={[...]} /> と /glossary の両方がここを読む。
 *
 * hawaiian は ʻokina（U+02BB）と kahakō を必ず付ける。sourceUrl と checkedAt は必須で、
 * 辞書（wehewehe.org）で確認した日を書く。tests/glossary.test.ts が形を検査する。
 */

export type TermCategory = "hula" | "olelo" | "aina" | "mea-ola" | "moolelo" | "moaukala";

export type Term = {
  id: string;
  hawaiian: string;
  /** 日本語の短い訳語（1行） */
  meaning: string;
  /** 補足。用法・流派差・語源など */
  note?: string;
  category: TermCategory;
  sourceUrl: string;
  checkedAt: string;
};

export const GLOSSARY: Term[] = [
  // ---- moolelo ----
  { id: "kumulipo", hawaiian: "Kumulipo", meaning: "起源、生命の源、神秘（PE: origin, genesis, source of life, mystery）。ハワイの創世系譜詠唱の題名", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kumulipo", checkedAt: "2026-09-18" },
  { id: "wa", hawaiian: "wā", meaning: "時代、時期。クムリポの16の章を指す", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=w%C4%81", checkedAt: "2026-09-18" },
  { id: "po", hawaiian: "pō", meaning: "夜、闇。神々の領域", note: "クムリポ前半の世界。ao と対になる", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=p%C5%8D", checkedAt: "2026-09-18" },
  { id: "ao", hawaiian: "ao", meaning: "光、昼、夜明け、世界", note: "pō から ao へ、が創世の向き", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ao", checkedAt: "2026-09-18" },
  { id: "koakoa", hawaiian: "koʻakoʻa", meaning: "サンゴ", note: "クムリポで最初に生まれる ʻukukoʻakoʻa（サンゴ虫）の語幹", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ko%CA%BBako%CA%BBa", checkedAt: "2026-09-18" },
  { id: "mookuauhau", hawaiian: "moʻokūʻauhau", meaning: "系譜、血統", note: "moʻo（連なり）＋ kūʻauhau（系図）。PE の見出しは kūʻauhau（moʻo kūʻauhau）", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C5%AB%CA%BBauhau", checkedAt: "2026-09-21" },
  { id: "koihonua", hawaiian: "koʻihonua", meaning: "系図の詠唱。mele koʻihonua はクムリポが属するジャンル", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ko%CA%BBihonua", checkedAt: "2026-09-18" },
  { id: "kinolau", hawaiian: "kinolau", meaning: "神が取る多くの身体（化身）。動物・植物・自然現象", note: "kino（体）＋ lau（多くの）。PE の見出しは kino lau（2語）。Laka の kinolau は kuahu に置く植物になる", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kino%20lau", checkedAt: "2026-09-21" },
  { id: "hookupu", hawaiian: "hoʻokupu", meaning: "供物、儀礼的な贈り物、貢納", note: "「成長させる」が語義。フラの場では kumu や神へ捧げる贈り物", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ho%CA%BBokupu", checkedAt: "2026-09-18" },
  { id: "aumakua", hawaiian: "ʻaumakua", meaning: "家族・個人の守護霊。神格化された祖先", note: "複数形は ʻaumākua。サメ・フクロウ・タコなどの姿を取る", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBaumakua", checkedAt: "2026-09-18" },
  { id: "kapu", hawaiian: "kapu", meaning: "禁忌、神聖、立入禁止。古代の宗教・社会体系そのものの名でもある", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kapu", checkedAt: "2026-09-18" },
  { id: "makahiki", hawaiian: "makahiki", meaning: "年。また、10〜11月頃に始まり約4か月続く Lono の祭りの季節", note: "戦は禁じられ、競技と貢納が行われた", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=makahiki", checkedAt: "2026-09-18" },
  { id: "akua", hawaiian: "akua", meaning: "神、霊的存在", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=akua", checkedAt: "2026-09-18" },
  { id: "heiau", hawaiian: "heiau", meaning: "神殿。石を積んだ祭祀の場", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=heiau", checkedAt: "2026-09-18" },
  { id: "ai-noa", hawaiian: "ʻai noa", meaning: "タブーを守らずに食べること（PE: to eat freely, without observance of taboos）。1819年に食の kapu が破られた出来事を指して使う", note: "ʻai（食べる）＋ noa（kapu から解かれた）", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBai%20noa", checkedAt: "2026-09-21" },
  { id: "kupua", hawaiian: "kupua", meaning: "半神。変身の力を持つ英雄・魔物", note: "Māui も Kamapuaʻa も kupua", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kupua", checkedAt: "2026-09-18" },
  { id: "kaona", hawaiian: "kaona", meaning: "隠された意味。詩歌における二重の意味、人や場所への暗示", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kaona", checkedAt: "2026-09-18" },
  { id: "moolelo", hawaiian: "moʻolelo", meaning: "物語、歴史、伝承、記録。語りの連なり全般", note: "moʻo（連なり）＋ ʻōlelo（ことば）", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=mo%CA%BBolelo", checkedAt: "2026-09-18" },
  { id: "kaao", hawaiian: "kaʻao", meaning: "空想的な物語、伝説、ロマンス", note: "moʻolelo より狭く、娯楽として語られることが多い。境目は絶対ではない", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ka%CA%BBao", checkedAt: "2026-09-18" },
  { id: "olelo-noeau", hawaiian: "ʻōlelo noʻeau", meaning: "ことわざ、詩的な言い回し", note: "Pukui『ʻŌlelo Noʻeau』（1983）が代表的な集成", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=no%CA%BBeau", checkedAt: "2026-09-18" },
  { id: "wiliwili", hawaiian: "wiliwili", meaning: "在来の落葉樹（Erythrina sandwicensis）。軽い材はサーフボードやカヌーの浮木に", note: "Māui が太陽を縛った木", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wiliwili", checkedAt: "2026-09-18" },
  { id: "alae", hawaiian: "ʻalae", meaning: "ハワイバン（ʻalae ʻula）。額が赤い水鳥", note: "Māui に火の秘密を明かした鳥", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBalae", checkedAt: "2026-09-18" },
  { id: "hiiaka", hawaiian: "Hiʻiaka", meaning: "Pele の妹たちの共通の冠称。最年少で最も名高いのが Hiʻiakaikapoliopele（Pele の懐の Hiʻiaka）", category: "moolelo", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D3488&l=en", checkedAt: "2026-09-18" },
  { id: "hopoe", hawaiian: "Hōpoe", meaning: "Puna で Pele に岩（balancing rock）に変えられた踊り手（PE）。Pele と Hiʻiaka の moʻolelo では Hiʻiaka の友として語られる", note: "普通語 hōpoe は「レフアの花が十分に開いた」状態を表す（PE hōpoe 1.）", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=h%C5%8Dpoe", checkedAt: "2026-09-21" },
  { id: "moo", hawaiian: "moʻo", meaning: "トカゲ、竜、水の精霊。Hiʻiaka が旅で戦う相手の総称", note: "「連なり」の意味の moʻo（moʻolelo, moʻokūʻauhau）と同じ綴り", category: "moolelo", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D125837&l=en", checkedAt: "2026-09-18" },
  { id: "lehua", hawaiian: "lehua", meaning: "ʻōhiʻa の花、またその木。ハワイ島の花", note: "Hiʻiaka と Hōpoe の象徴。Pele と Laka の両方の kinolau", category: "mea-ola", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D10707&l=en", checkedAt: "2026-09-18" },
  { id: "kahiki", hawaiian: "Kahiki", meaning: "海の向こうの土地、祖先の故郷。Pele が来た場所", note: "Tahiti と同源だが、特定の島より「彼方の地」の意で使う", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kahiki", checkedAt: "2026-09-18" },
  { id: "laka", hawaiian: "Laka", meaning: "フラと maile の女神（Wehewehe Community Dictionary）。kuahu に置く植物が Laka の kinolau とされる（Emerson 1909、講座 Moʻolelo Lesson 04）", note: "普通名詞 laka は「穏やかな、慣れた、引き寄せる」（PE）。カヌーの神 Laka を Kent 1986 は Kūōhiʻa Laka と同一とする", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=laka", checkedAt: "2026-09-21" },
  { id: "kapo", hawaiian: "Kapo", meaning: "Kalaipahoa の姉妹とされる女神。Pele の縁者とも語られる（Andrews 1865・Parker 1922。PE 1986 に項目は無い）", note: "Kapoʻulakīnaʻu の名、Laka との関係、呪術・憑依の神という面は講座 Moʻolelo Lesson 04（Beckwith・Emerson）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kapo", checkedAt: "2026-09-21" },
  { id: "kuahu", hawaiian: "kuahu", meaning: "祭壇。hālau の中に立て、Laka の依代と植物を置く", category: "hula", sourceUrl: "https://hilo.hawaii.edu/wehe/?a=q&q=kuahu", checkedAt: "2026-09-18" },
  { id: "maile", hawaiian: "maile", meaning: "香りのよい蔓（Alyxia stellata）。kuahu の標準植物、レイの代表", note: "4姉妹の半神としても語られる", category: "mea-ola", sourceUrl: "https://hilo.hawaii.edu/wehe/?a=q&q=maile", checkedAt: "2026-09-18" },
  { id: "ieie", hawaiian: "ʻieʻie", meaning: "森の木に絡む蔓（Freycinetia arborea）。kuahu の標準植物", category: "mea-ola", sourceUrl: "https://hilo.hawaii.edu/wehe/?a=q&q=ieie", checkedAt: "2026-09-18" },
  { id: "palapalai", hawaiian: "palapalai", meaning: "シダ（Microlepia）。kuahu の標準植物、lei poʻo の材料", category: "mea-ola", sourceUrl: "https://hilo.hawaii.edu/wehe/?a=q&q=palapalai", checkedAt: "2026-09-18" },
  { id: "hala-pepe", hawaiian: "hala pepe", meaning: "在来の木（Dracaena 属）。kuahu の標準植物", category: "mea-ola", sourceUrl: "https://hilo.hawaii.edu/wehe/?a=q&q=hala%20pepe", checkedAt: "2026-09-18" },
  { id: "pule", hawaiian: "pule", meaning: "祈り、祈ること", note: "pule kuahu は祭壇への祈り", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pule", checkedAt: "2026-09-18" },
  { id: "kukaepuaa", hawaiian: "kūkaepuaʻa", meaning: "在来の匍匐性の雑草（Digitaria pruriens）。語義は「豚の糞」", note: "Pukui-Elbert が Kamapuaʻa の植物形と記す", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kukaepua%CA%BBa", checkedAt: "2026-09-18" },
  { id: "uhaloa", hawaiian: "ʻuhaloa", meaning: "薬草（Waltheria indica var. americana）。根の内皮を喉の痛みに噛む", note: "Kamapuaʻa の植物形の一つ", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBuhaloa", checkedAt: "2026-09-18" },
  { id: "olomea", hawaiian: "olomea", meaning: "在来の木（Perrottetia sandwicensis）。硬い材を hau と擦り合わせて火を起こした", note: "Kamapuaʻa の植物形の一つ。同じ語が「豚や犬の、濃い縞や斑のある茶色」も指す", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=olomea", checkedAt: "2026-09-18" },
  { id: "hula-puaa", hawaiian: "hula puaʻa", meaning: "太った豚の歩みを真似て腰を左右に振るフラ", note: "ʻami puaʻa ともいう。Emerson（1909）は Kauaʻi 固有の、楽器を使わない演目として記録する", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=hula%20pua%CA%BBa", checkedAt: "2026-09-18" },
  { id: "poliahu", hawaiian: "Poliʻahu", meaning: "Mauna Kea の雪の女神", note: "Pukui-Elbert の直訳は Bosom goddess、Place Names は「胸の衣（＝雪）」、Beckwith 訳は Cold-bosom", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=poliahu", checkedAt: "2026-09-18" },
  { id: "hau", hawaiian: "hau", meaning: "冷たい、氷った。氷・霜・露・雪の総称、涼しい風", note: "hau kea は「白い雪」。海岸の木 hau（Hibiscus tiliaceus）は同じ綴りの別語", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=hau", checkedAt: "2026-09-18" },
  { id: "lilinoe", hawaiian: "Līlīnoe", meaning: "霧の女神。Poliʻahu の姉妹", note: "普通名詞 līlīnoe は「細かい霧、雨」。Mauna Kea の Puʻu Līlīnoe（12,956 ft）の名でもある", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lilinoe", checkedAt: "2026-09-18" },
  { id: "waiau", hawaiian: "Waiau", meaning: "Mauna Kea 山頂近くの湖（13,020 ft）。Place Names の直訳は「渦巻く水」。女神 Waiau の名でもある（講座 Moʻolelo Lesson 07、Maly 2005）", note: "普通名詞 waiau は「水の絶えない場所、いつでも水浴できる水」（Andrews・Parker の辞書。PE 1986 には見出しが無い）", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=waiau", checkedAt: "2026-09-21" },
  { id: "piko", hawaiian: "piko", meaning: "へそ、へその緒。比喩で血縁。丘や山の頂上", note: "新生児の piko を山頂へ納める実践がこの語で結ばれる", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=piko", checkedAt: "2026-09-18" },
  { id: "holua", hawaiian: "hōlua", meaning: "草の斜面を滑る古代のそり、およびその滑走路", note: "papa hōlua はそり、heʻe hōlua はそりに乗ること", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=holua", checkedAt: "2026-09-18" },
  { id: "kilu", hawaiian: "kilu", meaning: "瓢箪やヤシ殻の小容器。それを使う求愛の遊び", note: "詠唱しながら異性の前の的に投げ、当たれば口づけを求める", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kilu", checkedAt: "2026-09-18" },
  // ---- mea-ola ----
  { id: "maoli", hawaiian: "maoli", meaning: "在来の、本来の、真正の", note: "kanaka maoli＝ハワイ先住民。植物・動物では「在来種」の意", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=maoli", checkedAt: "2026-09-18" },
  { id: "pae-aina", hawaiian: "pae ʻāina", meaning: "諸島、群島", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pae%20%CA%BB%C4%81ina", checkedAt: "2026-09-18" },
  { id: "wao-akua", hawaiian: "wao akua", meaning: "神々の領域。人の暮らしから遠い高地の森", note: "人の領域 wao kanaka と対になる", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wao%20akua", checkedAt: "2026-09-18" },
  { id: "manu", hawaiian: "manu", meaning: "鳥", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=manu", checkedAt: "2026-09-18" },
  { id: "opeapea", hawaiian: "ʻōpeʻapeʻa", meaning: "ハワイアンホアリーコウモリ。現存する唯一の在来陸生哺乳類", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dpe%CA%BBape%CA%BBa", checkedAt: "2026-09-18" },
  { id: "kalo", hawaiian: "kalo", meaning: "タロイモ（Colocasia esculenta）。主食で、人の兄とされる", note: "辞書は「300以上の品種」と記す", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kalo", checkedAt: "2026-09-18" },
  { id: "ohia", hawaiian: "ʻōhiʻa", meaning: "ʻōhiʻa lehua の木（Metrosideros polymorpha）。在来林の主要樹種", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dhi%CA%BBa", checkedAt: "2026-09-18" },
  { id: "ki", hawaiian: "kī", meaning: "ティ（Cordyline fruticosa）。葉は lāʻī", note: "屋根葺き、供物を包む、フラのスカート、草履に使う。緑の葉は霊除けとされた（PE）", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%AB", checkedAt: "2026-09-18" },
  { id: "kukui", hawaiian: "kukui", meaning: "ククイ（Aleurites moluccana）。実の油で灯りを取った。州の木", note: "「光」「導き」の kaona", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kukui", checkedAt: "2026-09-18" },
  { id: "hala", hawaiian: "hala", meaning: "パンダナス（Pandanus tectorius）。葉 lauhala を編む", note: "「過ぎる・過ち」の意の hala と同綴りで、レイの kaona に使われる", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=hala", checkedAt: "2026-09-18" },
  { id: "mala", hawaiian: "mālama", meaning: "世話をする、守る、保つ", note: "mālama ʻāina＝土地を世話する", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=m%C4%81lama", checkedAt: "2026-09-18" },
  { id: "lei", hawaiian: "lei", meaning: "花・葉・貝などで作る首飾り、頭飾り", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lei", checkedAt: "2026-09-18" },
  { id: "honu", hawaiian: "honu", meaning: "アオウミガメ。カメ全般にも", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=honu", checkedAt: "2026-09-18" },
  { id: "kohola", hawaiian: "koholā", meaning: "ザトウクジラ", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kohol%C4%81", checkedAt: "2026-09-18" },
  { id: "mano", hawaiian: "manō", meaning: "サメ", note: "ʻaumakua として最もよく知られる生きもの", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=man%C5%8D", checkedAt: "2026-09-18" },
  { id: "naia", hawaiian: "naiʻa", meaning: "イルカ", note: "かつて女性には kapu だった", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=nai%CA%BBa", checkedAt: "2026-09-18" },
  { id: "ilioholoikauaua", hawaiian: "ʻīlioholoikauaua", meaning: "ハワイモンクアザラシ。「荒波を走る犬」", category: "mea-ola", sourceUrl: "https://sanctuaries.noaa.gov/magazine/4/hawaiian-monk-seal/", checkedAt: "2026-09-18" },
  { id: "konohiki", hawaiian: "konohiki", meaning: "ahupuaʻa の管理者。首長のもとで土地と漁業権を差配した", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=konohiki", checkedAt: "2026-09-18" },
  { id: "humuhumu", hawaiian: "humuhumu", meaning: "モンガラカワハギ類。州魚 humuhumunukunukuāpuaʻa は「豚の鼻の humuhumu」", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=humuhumu", checkedAt: "2026-09-18" },
  { id: "puaa", hawaiian: "puaʻa", meaning: "豚", note: "Lono の kinolau。辞書の語義3は山頂にかかる霧・雲の帯で、雨の兆し、Kamapuaʻa の雲の姿。野生化した puaʻa は森を荒らす", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pua%CA%BBa", checkedAt: "2026-09-18" },
  { id: "waiawi", hawaiian: "waiawī", meaning: "ストロベリーグアバ。在来林を駆逐する侵略種", category: "mea-ola", sourceUrl: "http://www.hear.org/species/psidium_cattleianum/", checkedAt: "2026-09-19" },
  { id: "ahinahina", hawaiian: "ʻāhinahina", meaning: "銀剣草（silversword）。Haleakalā の火口と Mauna Loa の高地に育つ（NPS）", category: "mea-ola", sourceUrl: "https://www.nps.gov/locations/hawaii/silverswords.htm", checkedAt: "2026-09-21" },
  { id: "nene", hawaiian: "nēnē", meaning: "ハワイガン。州鳥", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=n%C4%93n%C4%93", checkedAt: "2026-09-18" },
  { id: "ahupuaa", hawaiian: "ahupuaʻa", meaning: "山から海まで細長く延びる伝統の土地区分", note: "境界の石積み（ahu）に豚（puaʻa）の像や供物を置いたことに由来", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ahupua%CA%BBa", checkedAt: "2026-09-18" },
  { id: "iiwi", hawaiian: "ʻiʻiwi", meaning: "緋色のハワイミツスイ。羽は羽細工に使われた", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBi%CA%BBiwi", checkedAt: "2026-09-18" },
  { id: "apapane", hawaiian: "ʻapapane", meaning: "深紅のハワイミツスイ。lehua の蜜を吸う", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBapapane", checkedAt: "2026-09-18" },
  { id: "mamane", hawaiian: "māmane", meaning: "固有のマメ科高木。palila の餌", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=m%C4%81mane", checkedAt: "2026-09-18" },
  { id: "pueo", hawaiian: "pueo", meaning: "ハワイコミミズク。ʻaumakua としてよく語られる", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pueo", checkedAt: "2026-09-18" },
  { id: "io", hawaiian: "ʻio", meaning: "ハワイノスリ。王権の象徴とされた猛禽", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBio", checkedAt: "2026-09-18" },
  { id: "alala", hawaiian: "ʻalalā", meaning: "ハワイガラス。2002年に野生絶滅、再導入中", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBalal%C4%81", checkedAt: "2026-09-18" },
  // ---- hula ----
  { id: "hula", hawaiian: "hula", meaning: "フラ。踊り、踊り手、踊ること", category: "hula", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D107019&l=en", checkedAt: "2026-09-18" },
  { id: "kahiko", hawaiian: "kahiko", meaning: "古い、古代の。hula kahiko は詠唱と打楽器による様式", note: "様式を二分する専門用語としての定着は20世紀", category: "hula", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?d=D5942&l=en", checkedAt: "2026-09-18" },
  { id: "auana", hawaiian: "ʻauana", meaning: "さまよう、漂う。hula ʻauana は旋律楽器を伴う現代様式", note: "ʻauwana とも綴る", category: "hula", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?d=D1502&l=en", checkedAt: "2026-09-18" },
  { id: "hula-kui", hawaiian: "hula kuʻi", meaning: "Kalākaua 期（19世紀最後の四半期）に成立した「継ぎ合わせた」様式。西洋の要素と在来のフラを結ぶ", note: "kuʻi は「打つ」と「継ぐ」の両義", category: "hula", sourceUrl: "https://www.huapala.org/Hula_Steps.html", checkedAt: "2026-09-18" },
  { id: "haa", hawaiian: "haʻa", meaning: "膝を曲げた踊り。Kaeppler は heiau で pahu を伴って行われた儀礼の動きを hula ではなく haʻa と呼んで区別した", category: "hula", sourceUrl: "https://jashm.press.uillinois.edu/10.2/10-2Review_Kealiinohomoku103-107.pdf", checkedAt: "2026-09-18" },
  { id: "olapa", hawaiian: "ʻōlapa", meaning: "踊り手。hoʻopaʻa と対になる役割語", note: "PE は同じ見出しに「稲妻のように閃く」「木の名（Cheirodendron）」「踊り手」を並べる。葉のそよぎに由来するという説明は PE には無い", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dlapa", checkedAt: "2026-09-21" },
  { id: "hoopaa", hawaiian: "hoʻopaʻa", meaning: "詠唱と楽器を担う伴奏者。座るか膝をついて演じる。経験を積んだ者が務める", category: "hula", sourceUrl: "https://www.gutenberg.org/files/20299/20299-h/20299-h.htm", checkedAt: "2026-09-18" },
  { id: "oli", hawaiian: "oli", meaning: "詠唱。踊りを伴わないチャント", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=oli", checkedAt: "2026-09-18" },
  { id: "mele", hawaiian: "mele", meaning: "歌、詩、詠唱。詩の総称", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=mele", checkedAt: "2026-09-18" },
  { id: "pahu", hawaiian: "pahu", meaning: "ココヤシの幹をくり抜きサメ皮を張った太鼓（Andrews 1865・Kent 1986。PE は「箱、太鼓」）。heiau の儀礼と hula pahu に使う", note: "Laʻamaikahiki が Kahiki から伝えたという伝承は Kent 1986 の kāʻekeʻeke の項と Kaeppler（講座 Hula Lesson 02）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pahu", checkedAt: "2026-09-21" },
  { id: "ipu-heke", hawaiian: "ipu heke", meaning: "2つの瓢箪を継いだ打楽器。kahiko の拍を担う。hoʻopaʻa が打つ", note: "継ぎ目のない単式は ipu heke ʻole", category: "hula", sourceUrl: "https://data.bishopmuseum.org/ethnobotanydb/ethnobotany.php?b=d&ID=ipu", checkedAt: "2026-09-18" },
  { id: "puniu", hawaiian: "pūniu", meaning: "ココナツの殻に魚皮を張った膝太鼓。腿に結わえて打つ", category: "hula", sourceUrl: "https://keolamagazine.com/culture/hula-instruments/", checkedAt: "2026-09-18" },
  { id: "uliuli", hawaiian: "ʻulīʻulī", meaning: "種を詰めた瓢箪に柄と羽根飾りを付けたラトル。踊り手が持つ", category: "hula", sourceUrl: "https://www.kaahelehawaii.com/%CA%BBuli%CA%BBuli-the-gourd-rattles-of-hula/", checkedAt: "2026-09-18" },
  { id: "puili", hawaiian: "pūʻili", meaning: "細かく裂いた竹のラトル。両手に1本ずつ持って打ち鳴らす", category: "hula", sourceUrl: "https://organology.net/instrument/puili-puili/", checkedAt: "2026-09-18" },
  { id: "iliili", hawaiian: "ʻiliʻili", meaning: "水で磨かれた溶岩の小石。両手に持ちカスタネットのように打ち合わせる（Ke Ola Magazine）", note: "Kōloa の「生まれる石」が最良とされた（Images of Old Hawaiʻi）", category: "hula", sourceUrl: "https://keolamagazine.com/culture/hula-instruments/", checkedAt: "2026-09-21" },
  { id: "kalaau", hawaiian: "kālaʻau", meaning: "木の棒を一対で打ち合わせる楽器（Ke Ola Magazine。長短一対とするのは Emerson 1909）", category: "hula", sourceUrl: "https://keolamagazine.com/culture/hula-instruments/", checkedAt: "2026-09-18" },
  { id: "papa-hehi", hawaiian: "papa hehi", meaning: "足踏み板。kālaʻau と組み合わせ、足で板を踏みながら手で棒を打つ", category: "hula", sourceUrl: "https://keolamagazine.com/culture/hula-instruments/", checkedAt: "2026-09-18" },
  { id: "kaekeeke", hawaiian: "kāʻekeʻeke", meaning: "長さの違う竹管を打ちつけて鳴らす楽器", note: "古くはサメ皮の太鼓を指した二義がある", category: "hula", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?d=D147556&l=en", checkedAt: "2026-09-18" },
  { id: "ki-hoalu", hawaiian: "kī hōʻalu", meaning: "スラックキーギター。弦を「緩めた」変則調弦", category: "hula", sourceUrl: "https://www.piccom.org/programs/ki-hoalu-thats-slack-key-guitar", checkedAt: "2026-09-18" },
  { id: "kika-kila", hawaiian: "kīkā kila", meaning: "スチールギター。Joseph Kekuku（Lāʻie、1874年生）が考案した（Smithsonian）", category: "hula", sourceUrl: "https://www.smithsonianmag.com/smithsonian-institution/how-hawaiian-steel-guitar-changed-american-music-180972028/", checkedAt: "2026-09-18" },
  { id: "hapa-haole", hawaiian: "hapa haole", meaning: "英語とハワイ語が混じる、または全編英語の歌。Sonny Cunha が1903年の My Waikiki Mermaid 以降に広めた（Wikipedia）", category: "hula", sourceUrl: "https://en.wikipedia.org/wiki/Sonny_Cunha", checkedAt: "2026-09-18" },
  { id: "kaholo", hawaiian: "kāholo", meaning: "4カウントで一方の足を横へ出し、他方を引き寄せるステップ", note: "語義は「素早い、敏捷な」。現代の踊りに多い", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kaholo", checkedAt: "2026-09-18" },
  { id: "hela", hawaiian: "hela", meaning: "片足を前斜め45度に置き、反対の腰に体重を乗せて膝を曲げ、戻す。左右で繰り返す", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=hela", checkedAt: "2026-09-18" },
  { id: "uwehe", hawaiian: "ʻuwehe", meaning: "片足を上げ体重を反対の腰へ移し、下ろしながら両膝を前へ押し出す（踵を素早く上げる）。難しいステップ", note: "ʻuehe・ʻuweke の綴りも辞書にある", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBuwehe", checkedAt: "2026-09-18" },
  { id: "ami", hawaiian: "ʻami", meaning: "腰を回すステップ。ʻami kāhela（＝poepoe）・kūkū・ʻōniu・kuʻupau・ʻōpū などの下位分類", note: "Emerson は「骨盤と体幹の中心軸を円か楕円で振る」と記す", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBami", checkedAt: "2026-09-18" },
  { id: "oniu", hawaiian: "ʻōniu", meaning: "独楽。ʻami ʻōniu は腰が横8の字を描く", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dniu", checkedAt: "2026-09-18" },
  { id: "lele", hawaiian: "lele", meaning: "前へ歩き、一歩ごとに後ろの踵を上げる。後ろ向きにも", note: "lele ʻuwehe は ʻuwehe との複合", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lele", checkedAt: "2026-09-18" },
  { id: "kawelu", hawaiian: "kāwelu", meaning: "片足の踵で拍を取りながら、もう一方の足を前後に踏む", note: "huapala は「Kalākaua」と同一項目で載せる。流派差の例", category: "hula", sourceUrl: "https://www.huapala.org/Hula_Steps.html", checkedAt: "2026-09-18" },
  { id: "kii-wawae", hawaiian: "kiʻi wāwae", meaning: "右足を横・前・後ろの順に置き、左足で繰り返す", category: "hula", sourceUrl: "https://www.huapala.org/Hula_Steps.html", checkedAt: "2026-09-18" },
  { id: "ai-haa", hawaiian: "ʻai haʻa", meaning: "膝を曲げて低く踊るステップ・姿勢", note: "詠唱の様式名としては「力んだ喉声」の意（Emerson）", category: "hula", sourceUrl: "https://www.huapala.org/Hula_Steps.html", checkedAt: "2026-09-18" },
  { id: "kao", hawaiian: "kaʻo", meaning: "左右に揺れるステップ（教室用語）", note: "辞書の kaʻo は「乾いた、不毛の」のみ。huapala も「origin unknown」", category: "hula", sourceUrl: "https://www.huapala.org/Hula_Steps.html", checkedAt: "2026-09-18" },
  { id: "kumu-hula", hawaiian: "kumu hula", meaning: "フラの師。PE の kumu は 1「幹・基・源」、2「教師」で、kumu hula は 2 の複合語", note: "PE の見出しは kumu（kumu hula はその項の複合語）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kumu", checkedAt: "2026-09-21" },
  { id: "alakai", hawaiian: "alakaʻi", meaning: "導く者、リーダー。alakaʻi hula＝フラのリーダー", note: "Emerson 1909 の役職一覧には無い（kumu の代理 kokua kumu が近い）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=alaka%CA%BBi", checkedAt: "2026-09-18" },
  { id: "poopuaa", hawaiian: "poʻopuaʻa", meaning: "hālau の首席弟子。文字どおりには「豚の頭」", note: "Emerson では生徒が選ぶ代表で、kumu の命令の執行と罰金の徴収を担った", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=po%CA%BBopua%CA%BBa", checkedAt: "2026-09-18" },
  { id: "haumana", hawaiian: "haumana", meaning: "生徒、弟子", note: "PE の見出しは haumana（音節は hau.mana、hau.māna の両方）。haumāna は複数形として使われる", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=haumana", checkedAt: "2026-09-21" },
  { id: "kokua", hawaiian: "kōkua", meaning: "助け、助手", note: "教室の役職名としての用法は辞書に無い", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C5%8Dkua", checkedAt: "2026-09-18" },
  { id: "pau", hawaiian: "pāʻū", meaning: "女性のスカート。pāʻū hula＝踊りのスカート、pāʻū lāʻī＝ティの葉のスカート", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=p%C4%81%CA%BB%C5%AB", checkedAt: "2026-09-18" },
  { id: "kikepa", hawaiian: "kīkepa", meaning: "片方の腕の下から反対の肩へ掛ける巻き布", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%ABkepa", checkedAt: "2026-09-18" },
  { id: "lei-poo", hawaiian: "lei poʻo", meaning: "頭に着ける lei", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lei+po%CA%BBo", checkedAt: "2026-09-18" },
  { id: "lei-ai", hawaiian: "lei ʻāʻī", meaning: "肩に掛ける lei（maile など）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lei+%CA%BB%C4%81%CA%BB%C4%AB", checkedAt: "2026-09-18" },
  { id: "kupee", hawaiian: "kūpeʻe", meaning: "手首・足首の飾り。kūpeʻe wāwae は足のもの", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C5%ABpe%CA%BBe", checkedAt: "2026-09-18" },
  { id: "malo", hawaiian: "malo", meaning: "男性の腰布", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=malo", checkedAt: "2026-09-18" },
  { id: "kuhi", hawaiian: "kuhi", meaning: "指さす、身振りをする。話すとき、指揮するとき、hula を踊るときの身振り（PE: to point, gesture）", note: "hula kuhi lima は手の身振りと上体の揺れで踊る座りの hula。hoʻokuhi は「hula の身振りを教える」", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kuhi", checkedAt: "2026-09-24" },
  { id: "olohe", hawaiian: "ʻōlohe", meaning: "熟達した者。特に lua（格闘術）の達人で、hula の熟達者にも言う（PE 第2義）", note: "第1義は「裸の、毛の無い」。Emerson（1909）の綴りは olohe", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dlohe", checkedAt: "2026-09-24" },
  { id: "pali", hawaiian: "pali", meaning: "崖、断崖、急斜面。比喩で障害、困難（PE: cliff, precipice; figuratively, an obstacle, difficulty）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pali", checkedAt: "2026-09-24" },
  { id: "kihei", hawaiian: "kīhei", meaning: "肩掛け、ケープ。片方の肩にかけて結ぶ長方形の tapa の衣（PE）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%ABhei", checkedAt: "2026-09-24" },
  { id: "ahu-ula", hawaiian: "ʻahu ʻula", meaning: "羽毛のマント・ケープ。ʻōʻō や ʻiʻiwi などの羽でつくり、高位の首長と王が着た（PE）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBahu%20%CA%BBula", checkedAt: "2026-09-24" },
  { id: "holoku", hawaiian: "holokū", meaning: "ヨークと裾の引き（トレーン）のあるゆったりしたドレス", note: "muʻumuʻu はヨークとトレーンを省いた形", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=holok%C5%AB", checkedAt: "2026-09-18" },
  { id: "kahea", hawaiian: "kāhea", meaning: "呼ぶ、唱える。踊り手が次の節の冒頭を唱えて詠唱者に合図すること", note: "Emerson では hālau に入る合言葉の詠唱（mele kāhea）も指す", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%81hea", checkedAt: "2026-09-18" },
  { id: "hoomakaukau", hawaiian: "hoʻomākaukau", meaning: "準備する。「用意」の号令", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ho%CA%BBom%C4%81kaukau", checkedAt: "2026-09-18" },
  { id: "ae", hawaiian: "ʻae", meaning: "はい。同意する", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBae", checkedAt: "2026-09-18" },
  { id: "mele-inoa", hawaiian: "mele inoa", meaning: "名前の歌。人を讃える歌", category: "hula", sourceUrl: "https://www.gutenberg.org/cache/epub/20299/pg20299.txt", checkedAt: "2026-09-18" },
  { id: "mele-mai", hawaiian: "mele maʻi", meaning: "首長の誕生時に作られる、生殖器を讃える歌。速く陽気", category: "hula", sourceUrl: "https://wehewehe.org/gsdl2.85/cgi-bin/hdict?d=D11941&l=en", checkedAt: "2026-09-18" },
  { id: "mele-kanikau", hawaiian: "mele kanikau", meaning: "哀悼の歌", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kanikau", checkedAt: "2026-09-18" },
  { id: "mele-pana", hawaiian: "mele pana", meaning: "土地を讃える歌", category: "hula", sourceUrl: "https://kamehamehapublishing.org/wp-content/uploads/sites/38/2020/09/Hulili_Vol8_9.pdf", checkedAt: "2026-09-18" },
  { id: "pauku", hawaiian: "paukū", meaning: "節、スタンザ", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pauku", checkedAt: "2026-09-18" },
  { id: "kai", hawaiian: "kaʻi", meaning: "踊り手が観客の前に出る（入場）。その間の詠唱", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ka%CA%BBi", checkedAt: "2026-09-18" },
  { id: "hoi", hawaiian: "hoʻi", meaning: "退場の詠唱。踊りながら去る", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ho%CA%BBi", checkedAt: "2026-09-18" },
  { id: "haina", hawaiian: "haʻina", meaning: "歌の最後の2節（時にそれ以上）。主題または捧げる相手の名を繰り返す", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ha%CA%BBina", checkedAt: "2026-09-18" },
  { id: "puana", hawaiian: "puana", meaning: "歌の始まり、主音。要約の refrain", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=puana", checkedAt: "2026-09-18" },
  { id: "hoaeae", hawaiian: "hoʻāeae", meaning: "静かで感傷的な詠唱の様式。iʻi（声の震え）をほとんど立てない（Emerson 1909）", category: "hula", sourceUrl: "https://www.gutenberg.org/cache/epub/20299/pg20299.txt", checkedAt: "2026-09-18" },
  { id: "olioli", hawaiian: "olioli", meaning: "温かく、iʻi（声の震え）を極端にした詠唱の様式。語源は「喜ばしい」", category: "hula", sourceUrl: "https://www.gutenberg.org/cache/epub/20299/pg20299.txt", checkedAt: "2026-09-18" },
  { id: "kepakepa", hawaiian: "kepakepa", meaning: "速くリズミカルな朗唱。祈りに用いる", note: "Emerson では「隠語的な言い回し」を指す。指す範囲に注意", category: "hula", sourceUrl: "https://keolamagazine.com/culture/oli/", checkedAt: "2026-09-18" },
  { id: "pua", hawaiian: "pua", meaning: "花。PE 3. で「子孫、子ら」", note: "Kaulana Nā Pua の「花々」はハワイの人々", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pua", checkedAt: "2026-09-18" },
  { id: "halau", hawaiian: "hālau", meaning: "長屋。カヌー小屋、フラを教える場、集会所", note: "辞書の比較語源は PNP *folau（航海）。「hale＋lau」説は辞書に無い", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=halau", checkedAt: "2026-09-18" },
  { id: "uniki", hawaiian: "ʻūniki", meaning: "修了の儀式。hula に限らず lua など古い技芸に共通", note: "辞書は niki（結ぶ）に関係すると推定。Emerson は「初舞台」と定義", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=uniki", checkedAt: "2026-09-18" },
  { id: "ailolo", hawaiian: "ʻailolo", meaning: "修業の終わりを画す儀式。神に捧げた魚・犬・豚の頭、特に脳（lolo）を食べる（ʻai）ことから", note: "形容詞で「熟達した」の意も", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ailolo", checkedAt: "2026-09-18" },
  { id: "lama", hawaiian: "lama", meaning: "在来の木（Diospyros）。白く緻密な材で、神聖な囲いや kapu の用途に使われた", note: "kuahu の Laka の依代はこの木の無彫刻の木片", category: "hula", sourceUrl: "https://www.gutenberg.org/cache/epub/20299/pg20299.txt", checkedAt: "2026-09-18" },
  { id: "papa", hawaiian: "papa", meaning: "クラス、期。同じ時期に学び卒業した仲間", note: "Maiki Aiu Lake の「Papa Lehua」が有名", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=papa", checkedAt: "2026-09-18" },
  { id: "mele-kahea", hawaiian: "mele kāhea", meaning: "hālau に入る許可を請う詠唱。「Kūnihi ka mauna」が Emerson 1909 に合言葉として全文掲載されている", category: "hula", sourceUrl: "https://www.gutenberg.org/cache/epub/20299/pg20299.txt", checkedAt: "2026-09-18" },
  { id: "kupuna", hawaiian: "kupuna", meaning: "祖父母、年長者、祖先。複数形は kūpuna", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kupuna", checkedAt: "2026-09-18" },
  { id: "hoike", hawaiian: "hōʻike", meaning: "見せる、展示、発表会（PE: exhibition、school commencement）", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=h%C5%8D%CA%BBike", checkedAt: "2026-09-18" },
  { id: "wahine", hawaiian: "wahine", meaning: "女性。複数形は wāhine。Merrie Monarch の女性部門の名", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wahine", checkedAt: "2026-09-18" },
  { id: "kane", hawaiian: "kāne", meaning: "男性。Merrie Monarch の男性部門の名", note: "神 Kāne と同綴り", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%81ne", checkedAt: "2026-09-18" },
  { id: "haku-mele", hawaiian: "haku mele", meaning: "歌を作る、作詞作曲家。Nā Hōkū Hanohano の審査制部門の名", note: "haku＝編む、組む", category: "hula", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=haku%20mele", checkedAt: "2026-09-18" },
  // ---- olelo ----
  { id: "okina", hawaiian: "ʻokina", meaning: "声門閉鎖音を表す文字。「切ること、区切り」が原義", note: "ʻuʻina（はじける音）とも呼ぶ（HG p.11）。Unicode は U+02BB", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBokina", checkedAt: "2026-09-18" },
  { id: "kahako", hawaiian: "kahakō", meaning: "長母音を示す横線（マクロン）。長さと強勢の両方を表す", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "olelo-hawaii", hawaiian: "ʻōlelo Hawaiʻi", meaning: "ハワイ語。ʻōlelo は「ことば、話す」", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C5%8Dlelo", checkedAt: "2026-09-18" },
  { id: "puke-wehewehe", hawaiian: "puke wehewehe ʻōlelo", meaning: "辞書。wehewehe は「説明する」", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wehewehe", checkedAt: "2026-09-18" },
  { id: "ka-ke", hawaiian: "ka / ke", meaning: "定冠詞。a・e・o・k で始まる語の前では ke（例外語あり）", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ka", checkedAt: "2026-09-21" },
  { id: "na-plural", hawaiian: "nā", meaning: "複数の定冠詞。常に長母音", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=n%C4%81", checkedAt: "2026-09-21" },
  { id: "he-article", hawaiian: "he", meaning: "不定冠詞。「〜である」の He 文を作り、所有詞と組むと「持っている」", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=he", checkedAt: "2026-09-21" },
  { id: "kai-article", hawaiian: "kaʻi", meaning: "（文法用語）冠詞類。名詞の前に1つだけ付く", note: "ka/ke/nā/he と所有詞・指示詞を含む", category: "olelo", sourceUrl: "https://hawaiian-grammar.org/current/Elements%20of%20Hawaiian%20Grammar.pdf", checkedAt: "2026-09-18" },
  { id: "kinoa", hawaiian: "kinoʻā", meaning: "（文法用語）所有の a クラス。自分が作る・選べる・支配下にある関係", category: "olelo", sourceUrl: "https://hawaiian-grammar.org/current/Elements%20of%20Hawaiian%20Grammar.pdf", checkedAt: "2026-09-18" },
  { id: "kinoo", hawaiian: "kinoʻō", meaning: "（文法用語）所有の o クラス。選べない・生まれつき・身につける・乗る関係", category: "olelo", sourceUrl: "https://hawaiian-grammar.org/current/Elements%20of%20Hawaiian%20Grammar.pdf", checkedAt: "2026-09-18" },
  { id: "kakou", hawaiian: "kākou", meaning: "私たち全員（あなたを含む、3人以上）", note: "kā-＝包括、-kou＝複数。mākou は「あなたを含まない」", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%81kou", checkedAt: "2026-09-21" },
  { id: "kaua", hawaiian: "kāua", meaning: "あなたと私（2人）", note: "māua は「私ともう1人、あなたを含まない」", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%81ua", checkedAt: "2026-09-21" },
  { id: "keia", hawaiian: "kēia", meaning: "これ（話し手の近く）", note: "「この人＝私」の意で使うこともある", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=k%C4%93ia", checkedAt: "2026-09-18" },
  { id: "kena", hawaiian: "kēnā", meaning: "それ（聞き手の近く）", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=k%C4%93n%C4%81", checkedAt: "2026-09-18" },
  { id: "kela", hawaiian: "kēlā", meaning: "あれ（遠く）。物語では「前述の〜」", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=k%C4%93l%C4%81", checkedAt: "2026-09-18" },
  { id: "aia", hawaiian: "aia", meaning: "そこに〜がある（存在・場所文）。「〜次第」の意も", note: "eia は「ここに」。動詞マーカーを取らない", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=aia", checkedAt: "2026-09-18" },
  { id: "aaole", hawaiian: "ʻaʻole", meaning: "いいえ、〜ない。否定詞", note: "ʻaʻohe は ʻaʻole＋he の縮約", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBa%CA%BBole", checkedAt: "2026-09-18" },
  { id: "o-subject", hawaiian: "ʻo", meaning: "主語標識。人名・wai・ia の前に特によく立つ。同格も表す", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBo", checkedAt: "2026-09-18" },
  { id: "ia-object", hawaiian: "iā", meaning: "目的語・場所の標識 i が、代名詞・wai・人名・地名の前で取る形", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=i%C4%81", checkedAt: "2026-09-18" },
  { id: "ua", hawaiian: "ua", meaning: "完了の動詞マーカー。「〜した」「〜になった」", note: "否定文・従属節では i に替わる", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=ua", checkedAt: "2026-09-18" },
  { id: "e-ana", hawaiian: "e … ana", meaning: "未完了の動詞マーカー。継続・持続。時制は文脈で決まる", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "ke-nei", hawaiian: "ke … nei", meaning: "現在進行（話し手の近く）。ke … lā は遠い", category: "olelo", sourceUrl: "https://www.wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D7752", checkedAt: "2026-09-18" },
  { id: "e-imperative", hawaiian: "e", meaning: "命令・勧誘の動詞マーカー。従属節の標識にも", note: "否定命令は mai", category: "olelo", sourceUrl: "https://www.wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D2046", checkedAt: "2026-09-18" },
  { id: "ia-passive", hawaiian: "ʻia", meaning: "受動（と命令）の接尾辞。行為者は e で示す", category: "olelo", sourceUrl: "https://www.wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D4987", checkedAt: "2026-09-18" },
  { id: "hoo", hawaiian: "hoʻo-", meaning: "使役・他動化の接頭辞。「〜のふりをする」「〜のような」の意も", note: "辞書は hoʻo- を取って語基を引く", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=ho%CA%BBo-", checkedAt: "2026-09-18" },
  { id: "ana-nominalizer", hawaiian: "ʻana", meaning: "名詞化の助詞。「〜すること」", note: "辞書の nv/nvt/nvi/nvs は ʻana なしでも名詞", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBana", checkedAt: "2026-09-18" },
  { id: "hiki", hawaiian: "hiki", meaning: "できる、可能。hiki iā … ke ＋動詞", note: "loaʻa 型の状態動詞。ʻia を付けない", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=hiki", checkedAt: "2026-09-18" },
  { id: "aano", hawaiian: "ʻaʻano", meaning: "（文法用語）状態動詞。英語なら形容詞にあたる語もハワイ語では動詞", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "hamani", hawaiian: "hamani", meaning: "（文法用語）他動詞。目的語標識 i/iā を取る", category: "olelo", sourceUrl: "https://hawaiian-grammar.org/current/Elements%20of%20Hawaiian%20Grammar.pdf", checkedAt: "2026-09-18" },
  { id: "hehele", hawaiian: "hehele", meaning: "（文法用語）自動詞。目的語を取らず、強意の nui/loa も取らない", category: "olelo", sourceUrl: "https://hawaiian-grammar.org/current/Elements%20of%20Hawaiian%20Grammar.pdf", checkedAt: "2026-09-18" },
  { id: "mai-dir", hawaiian: "mai", meaning: "方向詞「こちらへ」。ほかに前置詞「〜から」、「もう少しで」、否定命令の4つの働きがある", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=mai", checkedAt: "2026-09-18" },
  { id: "aku", hawaiian: "aku", meaning: "方向詞「あちらへ、話し手から離れて」。時間では「〜前（nei と）」「これから（nei なし）」", note: "kūʻai mai＝買う、kūʻai aku＝売る", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=aku", checkedAt: "2026-09-18" },
  { id: "ae-dir", hawaiian: "aʻe", meaning: "方向詞「上へ、横へ、隣へ、次の」。聞き手の近く。比較級「より〜」にも", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=a%CA%BBe", checkedAt: "2026-09-18" },
  { id: "iho", hawaiian: "iho", meaning: "方向詞「下へ」。体の動作（食べる・考える）のあとでは再帰「自分で、自身」", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=iho", checkedAt: "2026-09-18" },
  { id: "na-no", hawaiian: "na / no", meaning: "na＝行為者（〜が作った、〜のもの）、no＝受益・主題（〜のための、〜について）、出身", note: "He mele na Kimo（Kimo 作）／He mele no Kimo（Kimo に捧ぐ）", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "e-vocative", hawaiian: "ē", meaning: "呼びかけ。名の前にも後ろにも置ける。「Ē Pua ē」", note: "行為者の e（短母音）とは別", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "me", hawaiian: "me", meaning: "〜と共に、〜で（道具）、〜のように", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "uka-kai", hawaiian: "uka / kai", meaning: "内陸側／海側。ma uka・ma kai で方角を言う。場所名詞", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "laila", hawaiian: "laila", meaning: "そこ。冠詞を取らない場所名詞。no laila＝だから", category: "olelo", sourceUrl: "https://puke.ulukau.org/ulukau-books/?a=d&d=EBOOK-HAWAIIANGRAMMAR", checkedAt: "2026-09-18" },
  { id: "anei-loc", hawaiian: "ʻaneʻi", meaning: "ここ。ma- の前で maʻaneʻi と1語に綴る", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=anei", checkedAt: "2026-09-18" },
  { id: "wai-interr", hawaiian: "wai", meaning: "誰。ʻO wai kou inoa?（名前は？）", note: "水の wai と同綴り", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=wai", checkedAt: "2026-09-18" },
  { id: "aha", hawaiian: "aha", meaning: "何、なぜ。He aha kēlā?（あれは何？）、No ke aha?（なぜ？）", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=aha", checkedAt: "2026-09-18" },
  { id: "hea", hawaiian: "hea", meaning: "どこ、どの。i hea / ma hea / mai hea / no hea", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=hea", checkedAt: "2026-09-18" },
  { id: "ehia", hawaiian: "ʻehia", meaning: "いくつ、いくら。Hola ʻehia?（何時？）", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBehia", checkedAt: "2026-09-18" },
  { id: "ahea", hawaiian: "āhea / ināhea", meaning: "いつ。āhea は未来、ināhea は過去", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%C4%81hea", checkedAt: "2026-09-21" },
  { id: "pehea", hawaiian: "pehea", meaning: "どう、どのように。Pehea ʻoe?（元気？）", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=pehea", checkedAt: "2026-09-18" },
  { id: "anei", hawaiian: "anei", meaning: "yes/no 疑問を示す助詞。語や句のあとに置く。省略可", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=anei", checkedAt: "2026-09-18" },
  { id: "aaohe", hawaiian: "ʻaʻohe", meaning: "無い、持っていない。ʻaʻole＋he の縮約。あとに k なし所有が続く", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=%CA%BBa%CA%BBohe", checkedAt: "2026-09-18" },
  { id: "ai-anaphoric", hawaiian: "ai", meaning: "照応の助詞。文頭に出した時・場所・理由の「穴」を動詞の後ろで指し示す。i … ai／e … ai", category: "olelo", sourceUrl: "https://www.wehewehe.org/gsdl2.85/cgi-bin/hdict?a=d&d=D362", checkedAt: "2026-09-18" },
  { id: "ina", hawaiian: "inā", meaning: "もし。ke は「もし・〜するとき（未来）」", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=in%C4%81", checkedAt: "2026-09-18" },
  { id: "aka", hawaiian: "akā", meaning: "しかし", category: "olelo", sourceUrl: "https://www.wehewehe.org/?q=ak%C4%81", checkedAt: "2026-09-18" },
  { id: "mamaka-kaiao", hawaiian: "Māmaka Kaiao", meaning: "現代語彙の辞書（2003）。Kōmike Huaʻōlelo と ʻAha Pūnana Leo が編纂。1,000語以上の新語", category: "olelo", sourceUrl: "https://uhpress.hawaii.edu/title/mamaka-kaiao-a-modern-hawaiian-vocabulary/", checkedAt: "2026-09-18" },
  { id: "no-intens", hawaiian: "nō", meaning: "強めの小辞。まさに、ちゃんと、かなり", note: "句末の小辞でいちばん前に立つ。前置詞 no（〜のために）とは別の語", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=n%C5%8D", checkedAt: "2026-09-18" },
  { id: "hoi-particle", hawaiian: "hoʻi", meaning: "強めの小辞。本当に。否定のあとで「〜も（ない）」", note: "動詞 hoʻi（帰る）と同じ綴り", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ho%CA%BBi", checkedAt: "2026-09-18" },
  { id: "paha", hawaiian: "paha", meaning: "たぶん、もしかすると。言い方を和らげる", note: "休止の直後には来ない", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=paha", checkedAt: "2026-09-18" },
  { id: "ka-particle", hawaiian: "kā", meaning: "驚き・軽い不満の小辞。なんと、なんだ", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=k%C4%81", checkedAt: "2026-09-18" },
  { id: "la-refrain", hawaiian: "lā", meaning: "歌の行末の囃子。直前の句を区切って際立たせる", note: "指示詞の lā、疑いの lā とは PE で別の番号", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=l%C4%81", checkedAt: "2026-09-18" },
  { id: "wale", hawaiian: "wale", meaning: "ただ、ひとりで。歌では「なんと〜なことか」の強め", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wale", checkedAt: "2026-09-18" },
  { id: "loa", hawaiian: "loa", meaning: "とても、いちばん。状態動詞のあとで強めになる", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=loa", checkedAt: "2026-09-18" },
  { id: "ae-song", hawaiian: "aʻe", meaning: "歌で動詞マーカー e の代わりに使う形", note: "PE aʻe 5.。e の置き換えなので動詞の前に立つ", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=a%CA%BBe", checkedAt: "2026-09-18" },
  { id: "ao-song", hawaiian: "aʻo", meaning: "歌で o（〜の）や ʻo（主語標識）の代わりに使う形", note: "PE aʻo 2.", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=a%CA%BBo", checkedAt: "2026-09-18" },
  { id: "e-intens", hawaiian: "ē", meaning: "強めの小辞。詩では行末の囃子にもなる", note: "呼びかけの ē とは PE で別の番号", category: "olelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%C4%93", checkedAt: "2026-09-18" },
  // ---- aina ----
  { id: "aina", hawaiian: "ʻāina", meaning: "土地、大地（PE: land, earth）。現代語では「国」の意でも使う（Māmaka Kaiao: country）", note: "「食べさせるもの」の含みで語られる（PE は Cf. ʻai, to eat）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C4%81ina", checkedAt: "2026-09-21" },
  { id: "mokupuni", hawaiian: "mokupuni", meaning: "島", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=mokupuni", checkedAt: "2026-09-18" },
  { id: "moku", hawaiian: "moku", meaning: "区（島の大区分）、島、切り離された部分", note: "動詞では「切れる」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=moku", checkedAt: "2026-09-18" },
  { id: "mauna", hawaiian: "mauna", meaning: "山。Mauna Loa＝長い山、Mauna Kea＝白い山", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=mauna", checkedAt: "2026-09-18" },
  { id: "puu", hawaiian: "puʻu", meaning: "丘、峰、噴石丘", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pu%CA%BBu", checkedAt: "2026-09-18" },
  { id: "pele-lava", hawaiian: "pele", meaning: "溶岩流、火山、噴火（女神 Pele に由来）", note: "lua pele＝火山（現代語）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=pele", checkedAt: "2026-09-18" },
  { id: "makani", hawaiian: "makani", meaning: "風。比喩で怒り、噂", note: "多くの風に名がある", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=makani", checkedAt: "2026-09-18" },
  { id: "ua-rain", hawaiian: "ua", meaning: "雨。「多くの雨には名があり、特定の場所と詩的に結びつく」（辞書）", note: "完了マーカーの ua と同綴り", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=ua", checkedAt: "2026-09-18" },
  { id: "koolau", hawaiian: "Koʻolau", meaning: "諸島の風上側（北東）。山脈の名にも", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=Ko%CA%BBolau", checkedAt: "2026-09-18" },
  { id: "kona", hawaiian: "Kona", meaning: "諸島の風下側（南西）。南西から吹く Kona 風の名でもある", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kona", checkedAt: "2026-09-18" },
  { id: "moae", hawaiian: "Moaʻe", meaning: "貿易風。Moaʻe kū＝強い貿易風", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=Moa%CA%BBe", checkedAt: "2026-09-18" },
  { id: "ili", hawaiian: "ʻili", meaning: "ahupuaʻa の下位区分（PE ʻili 5.）。ʻili ʻāina の貢納は ahupuaʻa の首長へ、ʻili kūpono は統治首長へ直接（PE の ʻili ʻāina・ʻili kūpono の項）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBili%20k%C5%ABpono", checkedAt: "2026-09-21" },
  { id: "loi", hawaiian: "loʻi", meaning: "灌漑した段々の田。主に kalo 用", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=lo%CA%BBi", checkedAt: "2026-09-18" },
  { id: "auwai", hawaiian: "ʻauwai", meaning: "用水路、溝", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBauwai", checkedAt: "2026-09-18" },
  { id: "loko-ia", hawaiian: "loko iʻa", meaning: "養魚池。loko kuapā（石垣の海面池）、loko puʻuone（砂州の背後の汽水池）、loko wai（淡水池）など", category: "aina", sourceUrl: "https://seagrant.soest.hawaii.edu/the-return-of-kuula/", checkedAt: "2026-09-18" },
  { id: "makaha", hawaiian: "mākāhā", meaning: "養魚池の水門（PE: sluice gate, as of a fish pond）", note: "細い枝を結わえた格子で、稚魚は入れるが成魚は出られない（Hawaiʻi Sea Grant の解説）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=m%C4%81k%C4%81h%C4%81", checkedAt: "2026-09-21" },
  { id: "muliwai", hawaiian: "muliwai", meaning: "河口、汽水域", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=muliwai", checkedAt: "2026-09-18" },
  { id: "pahoehoe", hawaiian: "pāhoehoe", meaning: "滑らかで途切れない溶岩。第2義は「サテン」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=p%C4%81hoehoe", checkedAt: "2026-09-18" },
  { id: "aa-lava", hawaiian: "ʻaʻā", meaning: "粗く砕けた溶岩。第1義は「燃える、赤く輝く」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBa%CA%BB%C4%81", checkedAt: "2026-09-18" },
  { id: "halemaumau", hawaiian: "Halemaʻumaʻu", meaning: "Kīlauea 山頂の火口。「ʻamaʻu（シダ）の家」（Place Names: fern house）", note: "Pele の住まいとされる（講座 Moʻolelo Lesson 03、NPS）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=Halema%CA%BBuma%CA%BBu", checkedAt: "2026-09-21" },
  { id: "kilauea", hawaiian: "Kīlauea", meaning: "「噴き出す、広く広がる」（Place Names: spewing, much spreading）。ハワイ島の活火山", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=K%C4%ABlauea", checkedAt: "2026-09-21" },
  { id: "kipuka", hawaiian: "kīpuka", meaning: "溶岩流に囲まれて残った古い土地と植生", category: "aina", sourceUrl: "https://www.nps.gov/havo/learn/nature/kipuka.htm", checkedAt: "2026-09-21" },
  { id: "amau", hawaiian: "ʻamaʻu", meaning: "固有のシダ（Sadleria）。Kamapuaʻa の化身の一つ。Halemaʻumaʻu の語源", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBama%CA%BBu", checkedAt: "2026-09-18" },
  { id: "kai-sea", hawaiian: "kai", meaning: "海、海水、潮、海辺の低地。makai＝海側へ", note: "nā kai ʻewalu＝8つの海（主島を隔てる海峡。PE の別見出し kai ʻewalu）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kai", checkedAt: "2026-09-21" },
  { id: "moana", hawaiian: "moana", meaning: "大洋、外海", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=moana", checkedAt: "2026-09-18" },
  { id: "nalu", hawaiian: "nalu", meaning: "波、うねり。heʻe nalu＝サーフィン（波を滑る）", note: "動詞では「思いめぐらす」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=nalu", checkedAt: "2026-09-18" },
  { id: "ale", hawaiian: "ʻale", meaning: "うねり、大波。ʻale poʻi＝砕ける波", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBale", checkedAt: "2026-09-18" },
  { id: "au-current", hawaiian: "au", meaning: "流れ、潮流。au kō malalo＝引き波の底流（PE: undertow。別見出し）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=au", checkedAt: "2026-09-21" },
  { id: "kohola-reef", hawaiian: "kohola", meaning: "礁原、干出する礁。kai kohola＝礁湖", note: "クジラの koholā（長母音）とは別", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kohola", checkedAt: "2026-09-18" },
  { id: "papahanaumokuakea", hawaiian: "Papahānaumokuākea", meaning: "北西ハワイ諸島の海洋国家記念物（2006年設置、2007年命名）。Papahānaumoku と Wākea の名を結ぶ", note: "2016年の拡張は同サイトの Expansion ページ（講座 ʻĀina Lesson 05）", category: "aina", sourceUrl: "https://www.papahanaumokuakea.gov/new-about/", checkedAt: "2026-09-21" },
  { id: "wahi-pana", hawaiian: "wahi pana", meaning: "伝説の地、名高い場所。語られることで名を得た場所", note: "pana の第3義「名高い場所」。第2義は「脈、鼓動」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wahi%20pana", checkedAt: "2026-09-18" },
  { id: "hono", hawaiian: "hono", meaning: "湾、谷（地名の語根）。Honolulu、Honokōhau", note: "hana- も同じ働き（Hanalei、Hanauma）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=hono", checkedAt: "2026-09-18" },
  { id: "wai", hawaiian: "wai", meaning: "真水、水（海水の kai と対）。Waipiʻo、Waimea、Waikīkī", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wai", checkedAt: "2026-09-18" },
  { id: "kanilehua", hawaiian: "ua Kanilehua", meaning: "Hilo で名高い霧のような雨。「lehua の花が飲む雨」", note: "Hilo Hanakahi, i ka ua Kanilehua", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=Kanilehua", checkedAt: "2026-09-18" },
  { id: "tuahine", hawaiian: "ua Tuahine", meaning: "Mānoa の霧雨。Kahalaopuna の物語の Kuahine にちなむ", note: "辞書の見出しは Kuahine だが「より一般には Tuahine」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kuahine", checkedAt: "2026-09-18" },
  { id: "lililehua", hawaiian: "ua Līlīlehua", meaning: "Pālolo（Oʻahu）と Waiehu（Maui）の風と雨。「lehua の冷え」", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=L%C4%ABl%C4%ABlehua", checkedAt: "2026-09-18" },
  { id: "apaapaa", hawaiian: "ʻĀpaʻapaʻa", meaning: "Kohala（ハワイ島）の強い風", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BB%C4%81pa%CA%BBapa%CA%BBa", checkedAt: "2026-09-18" },
  { id: "puulena", hawaiian: "Puʻulena", meaning: "Kīlauea と Puna の冷たい風", note: "Ua hala ka Puʻulena（Puʻulena は去った＝道を外れた。悲しみの含み）", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=Pu%CA%BBulena", checkedAt: "2026-09-18" },
  { id: "kiu", hawaiian: "Kiu", meaning: "強くやや冷たい北西の風。地方により Mālualua、Hoʻolua とも", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kiu", checkedAt: "2026-09-18" },
  { id: "naulu", hawaiian: "nāulu", meaning: "にわか雨、通り雨。Kawaihae・Waimea（Kauaʻi）・Kanaloa（Maui）の海風の名でも", category: "aina", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=n%C4%81ulu", checkedAt: "2026-09-18" },
  // ---- moaukala ----
  { id: "alii", hawaiian: "aliʻi", meaning: "首長、王族の階層。高位・下位の首長を含む", category: "moaukala", sourceUrl: "https://www.nps.gov/havo/learn/historyculture/alii.htm", checkedAt: "2026-09-18" },
  { id: "kahuna", hawaiian: "kahuna", meaning: "祭司の階層（NPS: the priestly class）。PE では priest のほか expert in any profession（あらゆる専門職の熟達者）", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kahuna", checkedAt: "2026-09-21" },
  { id: "makaainana", hawaiian: "makaʻāinana", meaning: "平民の階層（NPS: the commoner class）", category: "moaukala", sourceUrl: "https://www.nps.gov/havo/learn/historyculture/alii.htm", checkedAt: "2026-09-21" },
  { id: "kauwa", hawaiian: "kauwā", meaning: "最下層、追放者の階層", category: "moaukala", sourceUrl: "https://www.nps.gov/havo/learn/historyculture/alii.htm", checkedAt: "2026-09-18" },
  { id: "puuhonua", hawaiian: "puʻuhonua", meaning: "避難所。kapu を破った者や敗残兵が赦しを得る聖域", category: "moaukala", sourceUrl: "https://www.nps.gov/puho/learn/historyculture/index.htm", checkedAt: "2026-09-18" },
  { id: "waa-kaulua", hawaiian: "waʻa kaulua", meaning: "双胴のカヌー（PE: double canoe、字義は double-placed canoe）", note: "Hōkūleʻa は伝統的な航海カヌーの復元（講座 Mōʻaukala Lesson 01）", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=wa%CA%BBa%20kaulua", checkedAt: "2026-09-21" },
  { id: "kuhina-nui", hawaiian: "kuhina nui", meaning: "摂政に近い共同統治者の役職。初代は Kaʻahumanu", category: "moaukala", sourceUrl: "https://en.wikipedia.org/wiki/Ka%CA%BBahumanu", checkedAt: "2026-09-18" },
  { id: "mamalahoe", hawaiian: "Māmalahoe Kānāwai", meaning: "「折れた櫂の法」。老人・女性・子どもが道端で安全に休めるように、という Kamehameha I の法。州憲法第9条10節に明記", category: "moaukala", sourceUrl: "https://lrb.hawaii.gov/constitution/", checkedAt: "2026-09-18" },
  { id: "palapala", hawaiian: "palapala", meaning: "文書、読み書き。識字を指す語としても", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=palapala", checkedAt: "2026-09-18" },
  { id: "ea", hawaiian: "ea", meaning: "命、息。また主権。Ua mau ke ea o ka ʻāina i ka pono", category: "moaukala", sourceUrl: "https://kaiwakiloumoku.ksbe.edu/article/historical-snapshots-paulet-episode-1843", checkedAt: "2026-09-18" },
  { id: "mahele", hawaiian: "Māhele", meaning: "分割。1848年の土地分割（Great Māhele。PE: land division of 1848）。王・首長・政府への配分で、庶民の土地所有は1850年の Kuleana Act による", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=m%C4%81hele", checkedAt: "2026-09-21" },
  { id: "moi", hawaiian: "mōʻī", meaning: "王、君主", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=m%C5%8D%CA%BB%C4%AB", checkedAt: "2026-09-18" },
  { id: "kue", hawaiian: "kūʻē", meaning: "抵抗する、反対する。1897年の反併合請願の通称", category: "moaukala", sourceUrl: "https://guides.library.manoa.hawaii.edu/kuepetitions", checkedAt: "2026-09-18" },
  { id: "aloha-aina", hawaiian: "aloha ʻāina", meaning: "土地への愛。19世紀末には「愛国」と同義の政治語", category: "moaukala", sourceUrl: "https://evols.library.manoa.hawaii.edu/handle/10524/167", checkedAt: "2026-09-18" },
  { id: "hoohui-aina", hawaiian: "hoʻohui ʻāina", meaning: "土地を併せること＝併合", category: "moaukala", sourceUrl: "https://www.huapala.org/Kau/Kaulana_Na_Pua.html", checkedAt: "2026-09-18" },
  { id: "onipaa", hawaiian: "ʻonipaʻa", meaning: "不動、確固。字義は「動かぬこと」。Kamehameha V と Liliʻuokalani の座右銘（PE）", note: "1993年の転覆100年集会の名でもある（講座 Mōʻaukala Lesson 05）", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBonipa%CA%BBa", checkedAt: "2026-09-21" },
  { id: "punana-leo", hawaiian: "Pūnana Leo", meaning: "「声の巣」。ハワイ語イマージョンの幼稚園（1984年〜）", category: "moaukala", sourceUrl: "https://www.ahapunanaleo.org/history-hl-1", checkedAt: "2026-09-18" },
  { id: "kaiapuni", hawaiian: "Kaiapuni", meaning: "ハワイ語イマージョン教育プログラム（Ka Papahana Kaiapuni、1987年〜）", category: "moaukala", sourceUrl: "https://files.eric.ed.gov/fulltext/ED523186.pdf", checkedAt: "2026-09-18" },
  { id: "aupuni", hawaiian: "aupuni", meaning: "政府、国家", category: "moaukala", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=aupuni", checkedAt: "2026-09-18" },
  { id: "mokuaweoweo", hawaiian: "Mokuʻāweoweo", meaning: "Mauna Loa の山頂カルデラ。2022年11月の噴火はここから始まった", category: "aina", sourceUrl: "https://www.usgs.gov/volcanoes/mauna-loa/science/november-27-december-10-2022-eruption-mauna-loa", checkedAt: "2026-09-21" },
  { id: "amakihi", hawaiian: "ʻamakihi", meaning: "ハワイミツスイの一群（PE は a group、Loxops virens。現行の学名は Chlorodrepanis virens ほか）。羽は黄色と緑がかった色で、かつて羽毛衣に使われた", note: "低地の個体群が鳥マラリアへの耐性を進化させつつあることは講座 Nā Mea Ola Lesson 02（USGS）", category: "mea-ola", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=%CA%BBamakihi", checkedAt: "2026-09-21" },
  { id: "kuleana", hawaiian: "kuleana", meaning: "責任、権利、受け持ち。ahupuaʻa 内の小さな土地区画も指す（PE）", note: "1850年の Kuleana Act は講座 Mōʻaukala Lesson 03。年下の弟（人）が年上の兄（kalo）を世話する責任、の文脈でも使われる（講座 Nā Mea Ola Lesson 03）", category: "moolelo", sourceUrl: "https://wehe.hilo.hawaii.edu/?q=kuleana", checkedAt: "2026-09-21" },
];

export function findTerm(id: string): Term | undefined {
  return GLOSSARY.find((t) => t.id === id);
}
